#!/usr/bin/env bash
#is a challenge
check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                n_2=1
                for a in ${args[*]};
                do
                        if [ $count -gt 1 ];
                        then
                                n_2=$(echo $a*$n_2 | bc)
                        fi
                        count=$((count + 1))
                done
        else
                n_2=$3
        fi

        n_1=$2
        n_0=$(echo "$1" | tr ':' '=')

        result=$(echo "if($n_2 > $n_1) 1 else 0" | bc)
	        if ((result == 1)); then
		        n_cp=$n_1
		        n_1=$n_2
		        n_2=$n_cp
                fi

        echo "$n_0$n_1*$n_2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi
